version: "3.7"

services:
  webserver:
    image: my-php # php:7.4-apache
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./projects:/var/www/html/projects
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: housing

  mysql:
    image: mysql:8
    volumes:
      - housing-mysql-data:/var/lib/mysql
      - ./projects/leaflet_buffalo_map/data/housing.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: housing

  bokeh:
    image: my-python

    ports:
      - 5100:5100

volumes:
    housing-mysql-data: